# Generated by Django 5.2.5 on 2025-11-24 16:27

import FM.models
import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactoWeb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('apellido', models.CharField(blank=True, max_length=80, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('tipo_servicio', models.CharField(blank=True, max_length=120, null=True)),
                ('lugar_servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('region', models.CharField(blank=True, max_length=80, null=True)),
                ('comuna', models.CharField(blank=True, max_length=80, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('boletin', models.BooleanField(default=False)),
                ('acepta_privacidad', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contacto Web',
                'verbose_name_plural': 'Contactos Web',
            },
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('asunto', models.CharField(blank=True, max_length=200, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('presupuesto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('lugar_servicio', models.CharField(blank=True, max_length=150, null=True)),
                ('region', models.CharField(blank=True, max_length=80, null=True)),
                ('comuna', models.CharField(blank=True, max_length=80, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('PROCESO_PAGO', 'Proceso de pago'), ('COMPLETADA', 'Completada')], default='PENDIENTE', max_length=15)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('mp_preference_id', models.CharField(blank=True, max_length=80, null=True)),
                ('mp_payment_id', models.CharField(blank=True, max_length=80, null=True)),
                ('mp_payment_status', models.CharField(blank=True, max_length=40, null=True)),
                ('mp_init_point', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, help_text='p.ej. calderas', max_length=80, null=True, unique=True)),
                ('titulo', models.CharField(max_length=120)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('contenido_md', models.TextField(blank=True, null=True)),
                ('publicado', models.BooleanField(default=True)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('cantidad', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('precio_unit', models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)])),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='FM.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=160)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('comuna', models.CharField(blank=True, max_length=120, null=True)),
                ('region', models.CharField(blank=True, max_length=120, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['lat', 'lng'], name='FM_edificio_lat_3bf1bf_idx'), models.Index(fields=['comuna'], name='FM_edificio_comuna_e17fda_idx')],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='edificio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='FM.edificio'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='servicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='FM.servicio'),
        ),
        migrations.CreateModel(
            name='ServicioFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200)),
                ('respuesta_md', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='FM.servicio')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicioImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=FM.models.servicio_image_path)),
                ('alt', models.CharField(blank=True, max_length=200, null=True)),
                ('es_portada', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='FM.servicio')),
            ],
            options={
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisitaTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tecnico_slug', models.CharField(max_length=60)),
                ('tecnico_nombre', models.CharField(max_length=120)),
                ('cliente', models.CharField(max_length=150)),
                ('correo', models.EmailField(blank=True, max_length=254, null=True)),
                ('region', models.CharField(blank=True, max_length=80, null=True)),
                ('comuna', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitas', to='FM.cotizacion')),
            ],
            options={
                'ordering': ['fecha', 'hora', 'id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('rol', models.CharField(choices=[('ADMIN', 'Administrador'), ('TECNICO', 'Técnico'), ('CLIENTE', 'Cliente')], default='CLIENTE', max_length=10)),
                ('tipo_usuario', models.CharField(choices=[('PERSONA', 'Persona natural'), ('EMPRESA', 'Empresa')], default='PERSONA', max_length=10)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('empresa_nombre', models.CharField(blank=True, max_length=180, null=True)),
                ('empresa_rut', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('empresa_encargado', models.CharField(blank=True, max_length=150, null=True)),
                ('empresa_encargado_rut', models.CharField(blank=True, max_length=12, null=True)),
                ('empresa_ubicacion', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('acepta_boletin', models.BooleanField(default=False)),
                ('acepta_privacidad_at', models.DateTimeField(blank=True, null=True)),
                ('security_question', models.CharField(blank=True, max_length=200, null=True)),
                ('security_answer_hash', models.CharField(blank=True, max_length=256, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to=FM.models.documento_upload_path)),
                ('publico', models.BooleanField(default=True)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en', 'titulo'],
            },
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=90, null=True, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(blank=True, max_length=120, null=True)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('rut', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('especialidad', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('servicio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tecnicos', to='FM.servicio')),
            ],
            options={
                'ordering': ['nombre', 'apellido', 'id'],
                'indexes': [models.Index(fields=['slug'], name='FM_tecnico_slug_a053ed_idx'), models.Index(fields=['correo'], name='FM_tecnico_correo_5f91a0_idx'), models.Index(fields=['rut'], name='FM_tecnico_rut_24b492_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PLANIFICADO', 'Planificado'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PLANIFICADO', max_length=12)),
                ('fecha_programada', models.DateField(blank=True, null=True)),
                ('hora_inicio', models.DateTimeField(blank=True, null=True)),
                ('hora_fin', models.DateTimeField(blank=True, null=True)),
                ('cotizacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabajos', to='FM.cotizacion')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos', to='FM.edificio')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='trabajos', to='FM.servicio')),
            ],
            options={
                'indexes': [models.Index(fields=['estado'], name='FM_trabajo_estado_e51388_idx'), models.Index(fields=['edificio', 'estado'], name='FM_trabajo_edifici_24cec2_idx'), models.Index(fields=['fecha_programada'], name='FM_trabajo_fecha_p_006b18_idx')],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reset_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'used'], name='FM_password_code_c1058e_idx'), models.Index(fields=['expires_at'], name='FM_password_expires_120f9e_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=12)),
                ('token', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['code', 'used'], name='FM_logincod_code_4d08aa_idx'), models.Index(fields=['token', 'used'], name='FM_logincod_token_a86ed8_idx'), models.Index(fields=['expires_at'], name='FM_logincod_expires_b0f566_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['estado'], name='FM_cotizaci_estado_33f618_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['creado_en'], name='FM_cotizaci_creado__bd05f0_idx'),
        ),
    ]
