# Generated by Django 5.2.5 on 2025-11-24 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0001_initial'),
    ]

    def create_servicios(apps, schema_editor):
        Servicio = apps.get_model('FM', 'Servicio')
        servicios = [
            {
                "titulo": "Salas de calderas",
                "resumen": "Operacion segura, limpieza, calibracion y puesta a punto de calderas.",
                "orden": 1,
            },
            {
                "titulo": "Bombas y estanques",
                "resumen": "Revision de presiones, sellos y controles para flujo constante.",
                "orden": 2,
            },
            {
                "titulo": "Electricidad y respaldo",
                "resumen": "Tableros, protecciones y grupos electrógenos listos para emergencia.",
                "orden": 3,
            },
            {
                "titulo": "Portones automaticos",
                "resumen": "Automatizacion y servicio tecnico para portones corredizos y batientes.",
                "orden": 4,
            },
            {
                "titulo": "Extractores de aire",
                "resumen": "Soluciones de ventilacion para cocinas industriales y salas tecnicas.",
                "orden": 5,
            },
            {
                "titulo": "Paneles solares para agua caliente",
                "resumen": "Proyectos solares termicos para agua sanitaria y calefaccion.",
                "orden": 6,
            },
        ]
        for data in servicios:
            Servicio.objects.get_or_create(titulo=data["titulo"], defaults=data)

    def delete_servicios(apps, schema_editor):
        Servicio = apps.get_model('FM', 'Servicio')
        titulos = [
            "Salas de calderas",
            "Bombas y estanques",
            "Electricidad y respaldo",
            "Portones automaticos",
            "Extractores de aire",
            "Paneles solares para agua caliente",
        ]
        Servicio.objects.filter(titulo__in=titulos).delete()

    operations = [
        migrations.RunPython(create_servicios, delete_servicios),
    ]
