# Generated by Django 5.2.5 on 2025-11-24 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0003_tecnico'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='tecnico',
            new_name='FM_tecnico_slug_a053ed_idx',
            old_name='FM_tecnico_slug_idx',
        ),
        migrations.RenameIndex(
            model_name='tecnico',
            new_name='FM_tecnico_correo_5f91a0_idx',
            old_name='FM_tecnico_correo_idx',
        ),
        migrations.RenameIndex(
            model_name='tecnico',
            new_name='FM_tecnico_rut_24b492_idx',
            old_name='FM_tecnico_rut_idx',
        ),
    ]
