# Generated by Django 5.2.5 on 2025-11-24 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0005_region_comuna'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='region',
            name='FM_region_nombre_idx',
        ),
        migrations.RenameIndex(
            model_name='comuna',
            new_name='FM_comuna_region__64152b_idx',
            old_name='FM_comuna_region__nombre_idx',
        ),
    ]
