# Generated by Django 5.2.5 on 2025-11-24 18:56

from django.db import migrations
from django.utils.text import slugify


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0006_remove_region_fm_region_nombre_idx_and_more'),
    ]

    def populate_slugs(apps, schema_editor):
        Servicio = apps.get_model('FM', 'Servicio')
        for srv in Servicio.objects.all():
            if not getattr(srv, 'slug', None):
                srv.slug = slugify(srv.titulo)[:80]
                srv.save(update_fields=['slug'])

    operations = [
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
    ]
