# Generated by Django 5.2.5 on 2025-11-24 21:03

import FM.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FM', '0007_populate_servicio_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='cloud_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documento',
            name='cloud_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to=FM.models.documento_upload_path),
        ),
    ]
