# Generated by Django 5.2.5 on 2025-01-05 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FM", "0009_alter_cotizacion_estado_insumo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documento",
            name="cloud_public_id",
        ),
        migrations.RemoveField(
            model_name="documento",
            name="cloud_url",
        ),
    ]
