# Generated by Django 5.2.5 on 2025-01-05 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FM", "0010_remove_documento_cloud_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="storage_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="documento",
            name="storage_bucket",
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name="documento",
            name="storage_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
