# Generated by Django 5.2.5 on 2025-01-05 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FM", "0011_documento_storage_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="documento",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("FACTURA", "Factura"),
                    ("CONTRATO", "Contrato"),
                    ("IDENTIDAD", "Identidad"),
                    ("PERMISO", "Permiso"),
                    ("OTRO", "Otro"),
                ],
                default="OTRO",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="documento",
            name="tags",
            field=models.CharField(blank=True, help_text="Separar por comas", max_length=255, null=True),
        ),
    ]
